### ISSUE TITLE
Question about a message version

### ISSUE THREAD

**Issue by j0eun** [HarfangLab/endpoint-sec#39]
Hi, there! 
I have a question about the meaning of version in `es_message_t`.

When I monitoring with eslogger, all of messages have version 7(on macOS Sonoma 14.3). So I trust it is associated with the OS version, but not 100%. 

Does it mean a revision number of each messages updates? or directly represent the OS version? or both of them? If it has correlation with the OS version, what OS version does each version number refer to?

Thank you.

**Comment by poliorcetics** [comment]
> When I monitoring with eslogger, all of messages have version 7(on macOS Sonoma 14.3). So I trust it is associated with the OS version, but not 100%.

That's due to how the Endpoint Security Framework is updated: a new version necessarily comes with a new macOS version.

Conversely, a new macOS version may come *without* a new Endpoint Security version and so no increase in version number.

So, as you said, the two are associated but not 100%.

> what OS version does each version number refer to?

Note: It's documented by Apple here https://developer.apple.com/documentation/endpointsecurity/es_message_t/3366182-version

**Comment by j0eun** [comment]
Understood. I appreciate your answer! 😄
